### ISSUE TITLE
Servers from cfg are not appearing in GUI

### ISSUE THREAD

**Issue by wildbill22** [bdew-valheim/quickconnect#2]
I'm using Vortex and BepInEx to manage my mods.

Most mods put their cfg here for me:
D:\SteamLibrary\steamapps\common\Valheim\BepInEx\config
-OR in their folder-
C:\Users\xxxx\AppData\Roaming\Vortex\valheim\mods\0.9.0 ValheimPlus Windows Client-4-0-9-1614246431\config

This mod is putting it here (from a shortcut located here: D:\SteamLibrary\steamapps\common\Valheim\BepInEx\plugins):
C:\Users\xxxx\AppData\Roaming\Vortex\valheim\mods\Quick Connect-193-1-3-0-1614703656

I edited like so:
# Config file for QuickConnect mod
# Lines starting with # and empty lines are ignored

# Put one server per line
# name:addr:port:password

# addr can be ether IP or a fully qualified domain name

Awesome Server:127.0.0.1:2456:smellysocks
Another Server:myserver.example.com:2456:rockmyboars

Hello World:xx.xxx.xx.xxx:2456:myPassWord

But I don't see my server (I xxx out the IP, but used the actual above).

**Comment by bdew** [comment]
Don't put the config in plugins folder, it needs to go in the config folder like all other bepinex mods config files.
