### ISSUE TITLE
Upload to thunderstore.io

### ISSUE THREAD

**Issue by SavageCore** [bdew-valheim/quickconnect#3]
Would be great to have this uploaded to Thunderstore for use with [r2modman](https://valheim.thunderstore.io/package/ebkr/r2modman/) mod manager.

See [here](https://valheim.thunderstore.io/package/create/) for details!

**Comment by bdew** [comment]
It's on thunderstore now https://valheim.thunderstore.io/package/bdew/QuickConnect/
