### ISSUE TITLE
Scale Window Options

### ISSUE THREAD

**Issue by markjfisher** [bdew-valheim/quickconnect#5]
Can the configuration be added to scale the fonts and make the window larger please?

The functionality is perfect, but the connect window is incredibly small. I have a 4k monitor and it looks like this:
![image](https://user-images.githubusercontent.com/1616940/164764974-0c2910e8-f4c3-4913-98c1-1bab071180d2.png)

My wife is also using the mod, and she has visual difficulties, I was hoping it would be larger on her screen, but again it's very small and difficult for her to make out the buttons.

**Comment by BevansDesign** [comment]
Agreed, although I wonder if this is a BepInEx or Configuration Manager problem instead, since it seems to have the same issue and possibly handles the UI of the QuickConnect mod? (Just guessing since it looks the same.)

**Comment by markjfisher** [comment]
It looks like [the GUILayout.Button](https://docs.unity3d.com/ScriptReference/GUILayout.Button.html) object used to render the window [can take a GUIStyle argument](https://docs.unity3d.com/ScriptReference/GUIStyle.html), which can be used to set a font size.

I've not got an active dev env for unity/valheim, so it's hard for me to test this locally, but from the docs, it shouldn't be too hard to add config to control size and then use it.

**Comment by markjfisher** [comment]
With the patch, the window and fonts can be sized through configuration settings, e.g.
![image](https://user-images.githubusercontent.com/1616940/169139003-2bbf083d-170c-49bf-97ec-170a91a2ee7c.png)

**Comment by bdew** [comment]
Fixed, thanks to @markjfisher 
I tried messing with the code to scale the title bar too but couldn't get it looking right, i guess that would require a custom skin or maybe more IMGUI knowledge than i have.

**Comment by markjfisher** [comment]
Thanks!
