### ISSUE TITLE
Can there be a way to adjust it's size?

### ISSUE THREAD

**Issue by Ezzatoninan** [bdew-valheim/quickconnect#7]
Sorry no forums or chat for mods so had to post here...I was just curious if there was anyway to make it bigger overall I use a 3440x1440 screen size and it is so small I can barely read anything...just curious if there was anyway one could adjust it's size or UI. Other than that seems awesome!

**Comment by bdew** [comment]
with 1.5 that released yesterday you can change font sizes and window size in the config

**Comment by Ezzatoninan** [comment]
Ahhh ok Awesome TY for the reply!!!
________________________________
